tasks:
  - init: cargo test --package geoengine-operators --lib -- processing::meteosat::xgboost::tests::test_xg_ok --exact --nocapture --no-run

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - serayuzgur.crates
    - usernamehw.errorlens
    - vadimcn.vscode-lldb
    - hbenl.vscode-test-explorer
    - Swellaby.vscode-rust-test-adapter
    - hbenl.test-adapter-converter
    - asvetliakov.vscode-neovim
    - tamasfe.even-better-toml
    - aaron-bond.better-comments
    - https://github.com/rust-lang/rust-analyzer/releases/download/2022-07-11/rust-analyzer-linux-x64.vsix
