tasks:
  - init: cargo test --package geoengine-operators --lib -- processing::meteosat::xgboost::tests::test_xg_ok --exact --nocapture

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - serayuzgur.crates
    - usernamehw.errorlens
    - matklad.rust-analyzer
    - vadimcn.vscode-lldb
    - hbenl.vscode-test-explorer
    - Swellaby.vscode-rust-test-adapter
    - hbenl.test-adapter-converter
    - asvetliakov.vscode-neovim
    - tamasfe.even-better-toml
  