tasks:
  - init: cargo test --package geoengine-operators --lib -- processing::meteosat:.xgboost::tests::test_xg_ok --exact --nocapture

vscode:
  extensions:
    - anwar.resourcemonitor
    - tamasfe.even-better-toml
    - serayuzgur.crates
    - usernamehw.errorlens
    - matklad.rust-analyzer
    - vadimcn.vscode-lldb
    - hbenl.vscode-test-explorer
    - Swellaby.vscode-rust-test-adapter
