[package]
name = "geoengine-datatypes"
version = "0.1.0"
authors = [
    "Christian Beilschmidt <beilschmidt@mathematik.uni-marburg.de>",
    "Johannes Drönner <droenner@mathematik.uni-marburg.de>",
    "Michael Mattig <mattig@mathematik.uni-marburg.de>"
]
edition = "2021"

[features]
postgres = ["postgres-types"]
# This compiles Geo Engine Pro
pro = ["postgres"]

[dependencies]
arrow = { version = "8.0", features = ["simd"] }
float-cmp = "0.9"
gdal = "0.12"
geo = "0.18"
geojson = "0.22"
image = "0.23"
num-traits = "0.2"
ordered-float = { version= "2.0", features = ["serde"] }
paste = "1.0"
postgres-types = { version = "0.2", features = ["derive", "with-time-0_3", "with-uuid-0_8"], optional = true }
proj = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.7"
time = { version = "0.3", features = ["formatting", "macros", "parsing"] }
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }

[dev-dependencies]
criterion = "0.3"
ndarray = "0.14"
vega_lite_4 = { version = "0.6", features = ["ndarray", "show_vega"]}

[[bench]]
name = "multi_point_collection"
harness = false
